# Generated by Django 2.1.3 on 2019-03-30 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blackboard', '0002_auto_20190330_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runningsession',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
