# Generated by Django 2.1.3 on 2019-03-30 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190328_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 30, 15, 7, 48, 774338), verbose_name='date published'),
        ),
    ]
